### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by ashing-zhang** [ghliu/pytorch-ddpg#13]
Traceback (most recent call last):
  File "D:\Master\Codes\pytorch-ddpg\main.py", line 156, in <module>
    train(args.train_iter, agent, env, evaluate,
  File "D:\Master\Codes\pytorch-ddpg\main.py", line 44, in train
    observation2, reward, done, info = env.step(action)
  File "D:\AI\Software\Conda\Miniconda\envs\torch\lib\site-packages\gym\core.py", line 349, in step
    return self.env.step(self.action(action))
  File "D:\AI\Software\Conda\Miniconda\envs\torch\lib\site-packages\gym\core.py", line 353, in action
    raise NotImplementedError
NotImplementedError

**Comment by fuhaiwang** [comment]
You can change the code line#126 in main.py:
from
      env = NormalizedEnv(gym.make(args.env))
to
      env = gym.make(args.env)

Or you can do:
change the code line#8 and line#13 in normalized_env.py:
from
     def _action(self, action):   and def _reverse_action(self, action):
to
      def action(self, action):  and   def reverse_action(self, action):


Because the gym is updated (Maybe?). The function in class NormalizedEnv should delete "_". You can see the father class ActionWrapper in https://github.com/openai/gym/blob/master/gym/core.py


That's all!

**Comment by ashing-zhang** [comment]
Thank you sir.



---Original---
From: ***@***.***&gt;
Date: Fri, Nov 26, 2021 17:45 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ghliu/pytorch-ddpg] NotImplementedError (Issue #13)




 
You can change the code line#126 in main.py:
 from
 env = NormalizedEnv(gym.make(args.env))
 to
 env = gym.make(args.env)
 
Or you can do:
 change the code line#8 and line#13 in normalized_env.py:
 from
 def _action(self, action):   and def _reverse_action(self, action):
 to
 def action(self, action):  and   def reverse_action(self, action):
 
Because the gym is updated (Maybe?). The function in class NormalizedEnv should delete "_". You can see the father class ActionWrapper in https://github.com/openai/gym/blob/master/gym/core.py
 
That's all!
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
